name: Elixir Tests
run-name: ${{ github.actor }} is running unit tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Elixir
      uses: actions/setup-elixir@v2
      with:
        elixir-version: 1.14
        otp-version: 24.2

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Tests
      run: mix test

    - name: Compile
      run: mix compile
